[programs.devnet]
lowcapfun = "9wfonTvRiPDhLKZLCDWyjuZfJCA8T1ABUreFYPhJWd1Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
launch = "ts-node scripts/launch.ts"

