[package]
name = "lowcapfun"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"

